### ISSUE TITLE
About adding Tanh() at the end of the model

### ISSUE THREAD

**Issue by zhanghang1989** [darkstar112358/fast-neural-style#12]
Hi, when adding Tanh() at the end of the transformer model, I got error during the training. 
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`
Is there a way to fix this problem? Thanks!

**Comment by darkstar112358** [comment]
Can you share the code? I think because you are doing an inplace `tanh` this error is triggered.

**Comment by zhanghang1989** [comment]
I just add an `nn.Tanh()` as the last layer of the transformer model. Is there a non-inplace option for that layer? Thanks!

**Comment by darkstar112358** [comment]
I just added a fix for this in a new branch: https://github.com/darkstar112358/fast-neural-style/tree/tanh-fix . Can you add your `tanh` and try running it now. I tested it and it should be working.

**Comment by zhanghang1989** [comment]
It is working nicely. Thanks a lot!

**Comment by wjbKimberly** [comment]
Hi, I just meet the same issue. Could you pls share the fix way again?
